import { db } from '@/lib/db'
import { NextResponse } from 'next/server'

const newsImages = [
  '/news-meeting.png',
  '/news-infrastructure.png',
  '/news-ceremony.png',
  '/news-smart-city.png',
  '/news-health.png',
  '/news-road.png',
  '/news-industry.png',
  '/news-culture.png',
]

const departments = [
  'Engineering & Infrastructure',
  'IT & Digital Services',
  'Health Bureau',
  'Finance & Revenue',
  'Environment & Green Development',
  'Social & Labor Affairs',
  'Communication Department',
  'Legal Affairs',
  'Transport & Roads',
  'Culture & Tourism Bureau',
  'Procurement Office',
  'Education Bureau',
]

export async function POST() {
  try {
    /* ── Clear existing data ── */
    await db.newsArticle.deleteMany()
    await db.vacancy.deleteMany()
    await db.bid.deleteMany()

    /* ── Seed News Articles ── */
    const newsArticles = [
      {
        title: 'Dessie City Council Approves ETB 2.8 Billion Annual Budget',
        excerpt: 'The City Council has unanimously approved the municipal budget with significant allocations for infrastructure, education, and healthcare development across all 12 kebeles.',
        content: 'The Dessie City Council convened on July 12, 2025, and unanimously approved the annual municipal budget of ETB 2.8 billion. The budget allocates 35% to infrastructure and road construction, 25% to education and vocational training, 20% to healthcare and public health programs, and the remaining 20% to social services, administration, and debt service. Mayor Alemayehu Tadesse stated that this budget reflects the city administration\'s commitment to equitable development and improved public service delivery.',
        category: 'Press Release',
        image: '/news-meeting.png',
        author: 'Communication Department',
        status: 'published',
      },
      {
        title: 'Smart City Digital Platform Launched for Public Services',
        excerpt: 'Citizens can now access over 40 government services online including tax payments, permit applications, and service requests through the new digital platform.',
        content: 'Dessie City Administration has officially launched its Smart City Digital Platform, enabling citizens to access over 40 government services from their mobile phones and computers. The platform, developed in partnership with the IT & Digital Services Department, includes online tax payment, building permit applications, business license renewal, birth and marriage registration, and complaint submission. The platform is available in Amharic and English.',
        category: 'News',
        image: '/news-smart-city.png',
        author: 'IT & Digital Services',
        status: 'published',
      },
      {
        title: 'New 500-Hectare Industrial Zone Construction Begins',
        excerpt: 'The industrial zone on Kombolcha Road is expected to attract over ETB 10 billion in investment and create more than 5,000 permanent jobs for Dessie residents.',
        content: 'Construction of the 500-hectare Dessie Industrial Zone has officially commenced on the Kombolcha Road corridor. The project, funded through a combination of federal grants and municipal bonds, will feature modern manufacturing facilities, warehouses, and supporting infrastructure. The zone is designed to attract textile, agro-processing, and construction material manufacturers. The first phase, covering 150 hectares, is expected to be operational within 18 months.',
        category: 'News',
        image: '/news-industry.png',
        author: 'Engineering & Infrastructure',
        status: 'published',
      },
      {
        title: 'Dessie-Woldiya Highway Expansion Reaches 75% Completion',
        excerpt: 'The 45km road upgrade includes four-lane highways, modern bridges, and pedestrian pathways connecting Dessie to Woldiya.',
        content: 'The Ethiopian Roads Authority and Dessie City Administration have announced that the Dessie-Woldiya highway expansion project has reached 75% completion. The 45-kilometer road upgrade transforms the existing two-lane road into a modern four-lane highway with dedicated pedestrian walkways, cycling lanes, and five new bridges. The project also includes the construction of three rest areas and two truck parking facilities.',
        category: 'News',
        image: '/news-road.png',
        author: 'Transport & Roads',
        status: 'published',
      },
      {
        title: 'Annual Public Health Campaign Targets Malaria Prevention',
        excerpt: 'The Health Bureau launches a comprehensive malaria prevention campaign covering all 12 kebeles with free screening and treated mosquito net distribution.',
        content: 'The Dessie City Health Bureau has launched its annual malaria prevention campaign targeting all 12 kebeles. The campaign includes free malaria screening at 25 health posts, distribution of 50,000 insecticide-treated mosquito nets, and community awareness programs. Health professionals will also conduct indoor residual spraying in high-risk areas. The campaign runs through the rainy season and aims to reduce malaria cases by 60% compared to last year.',
        category: 'Event',
        image: '/news-health.png',
        author: 'Health Bureau',
        status: 'published',
      },
      {
        title: 'City Administration Signs MOU with Chinese Construction Firm',
        excerpt: 'A memorandum of understanding has been signed for the construction of 2,000 affordable housing units in the Dessie Integrated Housing Development Project.',
        content: 'Dessie City Administration has signed a Memorandum of Understanding with China Civil Engineering Construction Corporation (CCECC) for the development of 2,000 affordable housing units. The Dessie Integrated Housing Development Project will be constructed in three phases over four years, with the first phase delivering 700 housing units. The project includes schools, health clinics, commercial spaces, and green areas.',
        category: 'Press Release',
        image: '/news-ceremony.png',
        author: 'Communication Department',
        status: 'published',
      },
      {
        title: 'Major Water Supply Infrastructure Upgrade Completed',
        excerpt: 'The newly completed water treatment plant and distribution network will provide clean water to an additional 120,000 residents across the city.',
        content: 'The Dessie City Water Supply Upgrade Project has been completed, significantly expanding clean water access across the city. The project included the construction of a new water treatment plant with a capacity of 40,000 cubic meters per day, 85 kilometers of new distribution pipelines, and 15 new water reservoirs. The project, funded by the World Bank and the Ethiopian government, will serve an additional 120,000 residents.',
        category: 'News',
        image: '/news-infrastructure.png',
        author: 'Engineering & Infrastructure',
        status: 'published',
      },
      {
        title: 'Annual City Festival Celebrates Dessie\'s Rich Cultural Heritage',
        excerpt: 'The week-long festival features traditional music, dance, art exhibitions, and culinary showcases attracting visitors from across the Amhara region.',
        content: 'The annual Dessie City Festival kicked off this week with colorful celebrations showcasing the rich cultural heritage of Dessie and the Amhara region. The week-long festival, organized by the Culture & Tourism Bureau, features traditional music and dance performances, art exhibitions, handicraft displays, and a culinary showcase of authentic Amhara cuisine. The festival also includes a marathon, a youth talent show, and a business forum.',
        category: 'Event',
        image: '/news-culture.png',
        author: 'Culture & Tourism Bureau',
        status: 'published',
      },
      {
        title: 'Green City Initiative Plants 50,000 Trees Across Dessie',
        excerpt: 'The Environment & Green Development department leads a citywide tree planting campaign to combat deforestation and improve air quality.',
        content: 'The Dessie City Administration\'s Environment & Green Development department has completed the planting of 50,000 indigenous trees across all 12 kebeles as part of the Green City Initiative. The tree planting campaign involved over 10,000 volunteers including students, government employees, and community members. Species planted include Juniperus procera, Hagenia abyssinica, and Eucalyptus globulus.',
        category: 'Announcement',
        image: '/news-infrastructure.png',
        author: 'Environment & Green Development',
        status: 'published',
      },
      {
        title: 'Digital Literacy Program Enrolls 5,000 Youth in First Month',
        excerpt: 'The free digital literacy training program teaches computer basics, internet safety, and digital entrepreneurship to young residents aged 18-35.',
        content: 'The Dessie City Administration\'s Digital Literacy Program has enrolled over 5,000 young people in its first month of operation. The free training program, offered through the IT & Digital Services Department in partnership with local technical colleges, teaches computer basics, internet safety, email and document management, and digital entrepreneurship. Classes are held at 8 training centers across the city.',
        category: 'News',
        image: '/news-smart-city.png',
        author: 'IT & Digital Services',
        status: 'published',
      },
    ]

    const createdNews = await db.newsArticle.createMany({
      data: newsArticles.map((article, i) => ({
        ...article,
        createdAt: new Date(2025, 6, 12 - i),
      })),
    })

    /* ── Seed Vacancies ── */
    const vacancies = [
      {
        title: 'Senior Civil Engineer',
        department: 'Engineering & Infrastructure',
        type: 'Full-Time',
        salary: 'ETB 25,000 - 35,000',
        deadline: '2025-08-15',
        status: 'Open',
        description: 'Lead and manage civil engineering projects including road construction, building inspections, and infrastructure development across Dessie city.',
        requirements: JSON.stringify(['BSc in Civil Engineering', '5+ years experience in municipal engineering', 'Registered with Ethiopian Engineers Association', 'Proficiency in AutoCAD and project management software']),
      },
      {
        title: 'IT Systems Administrator',
        department: 'IT & Digital Services',
        type: 'Full-Time',
        salary: 'ETB 18,000 - 25,000',
        deadline: '2025-08-20',
        status: 'Open',
        description: 'Manage and maintain the city administration\'s IT infrastructure including servers, networks, and the Smart City digital platform.',
        requirements: JSON.stringify(['BSc in Computer Science or IT', '3+ years in systems administration', 'Knowledge of Linux, Windows Server, and cloud platforms', 'Relevant certifications preferred']),
      },
      {
        title: 'Public Health Officer',
        department: 'Health Bureau',
        type: 'Full-Time',
        salary: 'ETB 20,000 - 28,000',
        deadline: '2025-08-18',
        status: 'Open',
        description: 'Plan and implement public health programs including disease prevention, health education, and community health initiatives.',
        requirements: JSON.stringify(['MPH or BSc in Public Health', '3+ years in public health programs', 'Experience in community health planning', 'Knowledge of Ethiopian health policies']),
      },
      {
        title: 'Revenue Collection Officer',
        department: 'Finance & Revenue',
        type: 'Full-Time',
        salary: 'ETB 12,000 - 18,000',
        deadline: '2025-08-25',
        status: 'Open',
        description: 'Manage tax assessment, revenue collection, and financial reporting for the city administration\'s revenue department.',
        requirements: JSON.stringify(['BA in Accounting or Finance', '2+ years in tax or revenue collection', 'Knowledge of Ethiopian tax laws', 'Strong analytical and communication skills']),
      },
      {
        title: 'Environmental Protection Specialist',
        department: 'Environment & Green Development',
        type: 'Full-Time',
        salary: 'ETB 18,000 - 24,000',
        deadline: '2025-08-22',
        status: 'Open',
        description: 'Develop and implement environmental protection programs, conduct environmental impact assessments, and monitor pollution levels.',
        requirements: JSON.stringify(['BSc in Environmental Science or related field', '3+ years in environmental management', 'Experience with EIA processes', 'Knowledge of Ethiopian environmental regulations']),
      },
      {
        title: 'Social Worker',
        department: 'Social & Labor Affairs',
        type: 'Full-Time',
        salary: 'ETB 14,000 - 20,000',
        deadline: '2025-08-28',
        status: 'Open',
        description: 'Provide social support services, conduct community needs assessments, and implement social protection programs for vulnerable populations.',
        requirements: JSON.stringify(['BA in Social Work or Sociology', '2+ years in social services', 'Experience with vulnerable populations', 'Strong interpersonal and case management skills']),
      },
      {
        title: 'Public Relations Officer',
        department: 'Communication Department',
        type: 'Full-Time',
        salary: 'ETB 16,000 - 22,000',
        deadline: '2025-08-30',
        status: 'Open',
        description: 'Manage public communications, media relations, social media content, and public awareness campaigns for the city administration.',
        requirements: JSON.stringify(['BA in Journalism, Communications, or PR', '3+ years in public relations', 'Excellent Amharic and English writing skills', 'Experience with social media management']),
      },
      {
        title: 'Legal Advisor',
        department: 'Legal Affairs',
        type: 'Full-Time',
        salary: 'ETB 22,000 - 32,000',
        deadline: '2025-09-01',
        status: 'Open',
        description: 'Provide legal counsel on municipal law, review contracts and agreements, and represent the city administration in legal proceedings.',
        requirements: JSON.stringify(['LLB from accredited university', '4+ years in corporate or government law', 'Licensed to practice law in Ethiopia', 'Experience in municipal or administrative law preferred']),
      },
      {
        title: 'Transport Planner',
        department: 'Transport & Roads',
        type: 'Full-Time',
        salary: 'ETB 20,000 - 28,000',
        deadline: '2025-08-20',
        status: 'Open',
        description: 'Develop transport master plans, manage public transit systems, and coordinate road infrastructure projects.',
        requirements: JSON.stringify(['BSc in Transport Engineering or Urban Planning', '3+ years in transport planning', 'Experience with traffic modeling software', 'Knowledge of sustainable transport solutions']),
      },
      {
        title: 'Tourism Development Officer',
        department: 'Culture & Tourism Bureau',
        type: 'Full-Time',
        salary: 'ETB 15,000 - 22,000',
        deadline: '2025-08-25',
        status: 'Open',
        description: 'Develop and promote tourism programs, manage heritage sites, coordinate cultural events, and support local tourism businesses.',
        requirements: JSON.stringify(['BA in Tourism Management or related field', '2+ years in tourism development', 'Knowledge of Ethiopian heritage and culture', 'Marketing and event management skills']),
      },
      {
        title: 'Procurement Specialist',
        department: 'Procurement Office',
        type: 'Full-Time',
        salary: 'ETB 18,000 - 25,000',
        deadline: '2025-09-05',
        status: 'Open',
        description: 'Manage procurement processes, evaluate bids, ensure compliance with public procurement laws, and maintain vendor relationships.',
        requirements: JSON.stringify(['BA in Procurement, Supply Chain, or Business', '3+ years in public procurement', 'Knowledge of Ethiopian procurement laws', 'Professional certification in procurement preferred']),
      },
      {
        title: 'Secondary School Teacher',
        department: 'Education Bureau',
        type: 'Full-Time',
        salary: 'ETB 14,000 - 20,000',
        deadline: '2025-08-30',
        status: 'Open',
        description: 'Teach secondary school students in designated subjects, develop lesson plans, and participate in curriculum development activities.',
        requirements: JSON.stringify(['BEd in relevant teaching subject', 'Teaching certification', '2+ years teaching experience', 'Strong classroom management skills']),
      },
      {
        title: 'Data Entry Clerk',
        department: 'Finance & Revenue',
        type: 'Contract',
        salary: 'ETB 8,000 - 12,000',
        deadline: '2025-08-15',
        status: 'Open',
        description: 'Enter and maintain financial records, process data entry for tax assessments, and generate routine financial reports.',
        requirements: JSON.stringify(['Diploma in Accounting or IT', '1+ year data entry experience', 'Proficiency in Microsoft Office', 'Typing speed of 40+ WPM']),
      },
      {
        title: 'Urban Planner',
        department: 'Engineering & Infrastructure',
        type: 'Full-Time',
        salary: 'ETB 22,000 - 30,000',
        deadline: '2025-09-10',
        status: 'Open',
        description: 'Develop and implement urban planning strategies, review building plans for compliance, and coordinate city development projects.',
        requirements: JSON.stringify(['MSc or BSc in Urban Planning', '4+ years in urban planning', 'Experience with GIS and planning software', 'Knowledge of Ethiopian building codes']),
      },
      {
        title: 'Labor Inspector',
        department: 'Social & Labor Affairs',
        type: 'Full-Time',
        salary: 'ETB 16,000 - 22,000',
        deadline: '2025-09-01',
        status: 'Open',
        description: 'Conduct workplace inspections, enforce labor laws, investigate complaints, and promote safe working conditions across the city.',
        requirements: JSON.stringify(['BA in Law, Social Science, or related field', '3+ years in labor inspection or related field', 'Knowledge of Ethiopian labor laws', 'Investigation and report writing skills']),
      },
    ]

    const createdVacancies = await db.vacancy.createMany({
      data: vacancies.map(v => ({ ...v, approvalStatus: 'approved', status: 'Open' })),
    })

    /* ── Seed Bids/Tenders ── */
    const bids = [
      {
        title: 'Construction of 5km Asphalt Road in Kebele 03',
        reference: 'DCA/PROC/2025-001',
        category: 'Construction',
        deadline: '2025-08-30',
        status: 'Open',
        description: 'Construction of a 5-kilometer two-lane asphalt road with drainage systems, pedestrian walkways, and street lighting in Kebele 03.',
        budget: 'ETB 45,000,000',
        requirements: JSON.stringify(['Minimum Grade 4 GC registration', '5+ years road construction experience', 'Valid tax clearance certificate', 'Performance guarantee of 3%']),
      },
      {
        title: 'Supply of 500 Desktop Computers for City Offices',
        reference: 'DCA/PROC/2025-002',
        category: 'IT',
        deadline: '2025-08-20',
        status: 'Open',
        description: 'Supply and installation of 500 desktop computers with monitors, keyboards, and mice for various city administration offices.',
        budget: 'ETB 18,500,000',
        requirements: JSON.stringify(['Authorized distributor of recognized brands', 'Minimum 2 years warranty', 'On-site installation and training', 'Spare parts availability for 5 years']),
      },
      {
        title: 'Consultancy Services for City Master Plan Update',
        reference: 'DCA/PROC/2025-003',
        category: 'Consulting',
        deadline: '2025-09-15',
        status: 'Open',
        description: 'Consultancy services to update the Dessie City Master Plan including land use, transport, infrastructure, and environmental planning.',
        budget: 'ETB 12,000,000',
        requirements: JSON.stringify(['Firm with urban planning experience', 'Lead consultant with 10+ years experience', 'Previous master plan work in Ethiopia', 'Multi-disciplinary team capability']),
      },
      {
        title: 'Office Furniture Supply for New Administration Building',
        reference: 'DCA/PROC/2025-004',
        category: 'Supplies',
        deadline: '2025-08-25',
        status: 'Open',
        description: 'Supply and delivery of office furniture including desks, chairs, filing cabinets, and meeting room furniture for the new administration building.',
        budget: 'ETB 8,500,000',
        requirements: JSON.stringify(['Manufacturer or authorized dealer', 'Minimum 3 years furniture supply experience', 'Delivery within 30 days of contract', '12-month warranty on all items']),
      },
      {
        title: 'Construction of Modern Public Market in Kebele 07',
        reference: 'DCA/PROC/2025-005',
        category: 'Construction',
        deadline: '2025-09-20',
        status: 'Open',
        description: 'Design and construction of a modern public market with 200 vendor stalls, cold storage, parking, and sanitation facilities.',
        budget: 'ETB 120,000,000',
        requirements: JSON.stringify(['Grade 3 or above GC registration', 'Previous market construction experience', 'Joint venture with local subcontractors required', '18-month completion timeline']),
      },
      {
        title: 'IT Infrastructure and Network Setup for Smart City',
        reference: 'DCA/PROC/2025-006',
        category: 'IT',
        deadline: '2025-09-10',
        status: 'Open',
        description: 'Design, supply, and installation of comprehensive IT infrastructure including fiber optic network, servers, and security systems for the Smart City platform.',
        budget: 'ETB 35,000,000',
        requirements: JSON.stringify(['Registered IT company with 5+ years experience', 'Certified network engineers on staff', 'Partnership with major technology vendors', '24/7 support capability']),
      },
      {
        title: 'Waste Management Services for City Wide Operations',
        reference: 'DCA/PROC/2025-007',
        category: 'Services',
        deadline: '2025-08-28',
        status: 'Open',
        description: 'Provision of comprehensive waste collection, transportation, and disposal services for all 12 kebeles of Dessie city.',
        budget: 'ETB 28,000,000',
        requirements: JSON.stringify(['Waste management license', 'Fleet of collection vehicles', 'Proper disposal site access', 'Experience in municipal waste management']),
      },
      {
        title: 'Construction of Primary School in Kebele 10',
        reference: 'DCA/PROC/2025-008',
        category: 'Construction',
        deadline: '2025-09-05',
        status: 'Open',
        description: 'Construction of a fully equipped primary school with 16 classrooms, library, laboratory, administrative offices, and playground.',
        budget: 'ETB 55,000,000',
        requirements: JSON.stringify(['Grade 3 or above GC registration', 'School construction experience', 'Educational facility standards knowledge', '12-month completion timeline']),
      },
      {
        title: 'Security Services for Government Buildings',
        reference: 'DCA/PROC/2025-009',
        category: 'Services',
        deadline: '2025-08-22',
        status: 'Open',
        description: 'Provision of professional security guard services for 15 government buildings including city hall, tax office, and health facilities.',
        budget: 'ETB 15,000,000',
        requirements: JSON.stringify(['Licensed security company', 'Trained and vetted security personnel', '24/7 coverage capability', 'Insurance coverage for all personnel']),
      },
      {
        title: 'Supply of Medical Equipment for City Health Centers',
        reference: 'DCA/PROC/2025-010',
        category: 'Supplies',
        deadline: '2025-09-12',
        status: 'Open',
        description: 'Supply and installation of medical equipment including diagnostic tools, laboratory equipment, and patient monitoring systems for 5 city health centers.',
        budget: 'ETB 22,000,000',
        requirements: JSON.stringify(['Medical equipment supplier with MOH registration', 'WHO-GMP certified products', 'Installation and training included', '5-year warranty and maintenance agreement']),
      },
      {
        title: 'Road Maintenance and Rehabilitation Services',
        reference: 'DCA/PROC/2025-011',
        category: 'Construction',
        deadline: '2025-09-25',
        status: 'Open',
        description: 'Routine maintenance and rehabilitation of 80km of city roads including pothole repair, resurfacing, and drainage maintenance.',
        budget: 'ETB 65,000,000',
        requirements: JSON.stringify(['Grade 3 or above GC registration', 'Road maintenance equipment fleet', '5+ years road maintenance experience', 'Ability to mobilize within 15 days']),
      },
      {
        title: 'Feasibility Study for Solar Power Plant',
        reference: 'DCA/PROC/2025-012',
        category: 'Consulting',
        deadline: '2025-09-18',
        status: 'Open',
        description: 'Conduct a comprehensive feasibility study for a 10MW solar power plant including site assessment, technical design, and financial analysis.',
        budget: 'ETB 4,500,000',
        requirements: JSON.stringify(['Renewable energy consultancy experience', 'Solar project feasibility track record', 'Registered engineering firm', 'Team with electrical and financial analysts']),
      },
    ]

    const createdBids = await db.bid.createMany({
      data: bids.map(b => ({ ...b, approvalStatus: 'approved', status: 'Open' })),
    })

    return NextResponse.json({
      success: true,
      message: 'Database seeded successfully',
      counts: {
        newsArticles: createdNews.count,
        vacancies: createdVacancies.count,
        bids: createdBids.count,
      },
    })
  } catch (error) {
    console.error('Seed error:', error)
    return NextResponse.json(
      { success: false, message: 'Failed to seed database', error: String(error) },
      { status: 500 }
    )
  }
}